POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "atualizando",
    "description": "teste descrição",
    "price": 1800,
    "image": "https://unsplash.com/pt-br/fotografias/fotografia-aerea-da-cidade-rt8WwWTh0V0"
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/68065bd6edf16e576be12c1b

###
DELETE  http://localhost:3000/api/services/68065ee89d336cf1e46b67e8

###
PUT http://localhost:3000/api/services/68065bd6edf16e576be12c1b
Content-Type: application/json

{
    "name": "TESTE ATUALIZAÇÃO",
    "description": "teste descrição",
    "price": 2000,
    "image": "https://unsplash.com/pt-br/fotografias/fotografia-aerea-da-cidade-rt8WwWTh0V0"
}

###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
   "title": "Meu evento 3",
   "author": "Elton",
   "description": "Uma festa de aniversario",
   "budget": 3000,
   "image": "https://unsplash.com/pt-br/fotografias/fotografia-aerea-da-cidade-rt8WwWTh0V0",
   "services": [
        {
            "name": "algum serviço 1",
            "description": "teste descrição",
            "price": 3000,
            "image": "https://unsplash.com/pt-br/fotografias/fotografia-aerea-da-cidade-rt8WwWTh0V0"
        },
        {
            "name": "algum serviço 2",
            "description": "teste descrição",
            "price": 1800,
            "image": "https://unsplash.com/pt-br/fotografias/fotografia-aerea-da-cidade-rt8WwWTh0V0"
        }
   ]
}

