POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "algum serviço",
    "description": "alguma descrição",
    "price": 1400,
    "image": "https://unsplash.com/pt-br/fotografias/fotografia-aerea-da-cidade-rt8WwWTh0V0"
}
